CREATE DATABASE IF NOT EXISTS company;

USE company;

CREATE TABLE employees (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) DEFAULT NULL,
    salary INT UNSIGNED DEFAULT NULL,
    PRIMARY KEY(id)
);

DESCRIBE employees;